/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as VerifyEmailRouteImport } from "./pages/verify-email"
import { Route as SignupOrganizationRouteImport } from "./pages/signup-organization"
import { Route as ResetPasswordRouteImport } from "./pages/reset-password"
import { Route as RegisterRouteImport } from "./pages/register"
import { Route as LoginRouteImport } from "./pages/login"
import { Route as ForgotPasswordRouteImport } from "./pages/forgot-password"
import { Route as R404RouteImport } from "./pages/404"
import { Route as IndexRouteImport } from "./pages/index"

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const SignupOrganizationRoute = SignupOrganizationRouteImport.update({
  id: "/signup-organization",
  path: "/signup-organization",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: "/404",
  path: "/404",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/signup-organization": typeof SignupOrganizationRoute
  "/verify-email": typeof VerifyEmailRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/signup-organization": typeof SignupOrganizationRoute
  "/verify-email": typeof VerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/signup-organization": typeof SignupOrganizationRoute
  "/verify-email": typeof VerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/404"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/signup-organization"
    | "/verify-email"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/404"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/signup-organization"
    | "/verify-email"
  id:
    | "__root__"
    | "/"
    | "/404"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/signup-organization"
    | "/verify-email"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupOrganizationRoute: typeof SignupOrganizationRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signup-organization": {
      id: "/signup-organization"
      path: "/signup-organization"
      fullPath: "/signup-organization"
      preLoaderRoute: typeof SignupOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password": {
      id: "/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/404": {
      id: "/404"
      path: "/404"
      fullPath: "/404"
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupOrganizationRoute: SignupOrganizationRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
